###3.3.2 예측점수 구하기

In [ ]:
print('사용자 평점\n', df_ratings_movies.values)
print('영화별 유사도\n', movies_similarity)
print('영화별 유사도\n', item_based_collab.values)
print('내적\n', df_ratings_movies.values.dot(item_based_collab.values))

사용자 평점
 [[4. 0. 4. 0. 5.]
 [3. 3. 4. 5. 5.]
 [3. 5. 0. 3. 0.]]
영화별 유사도
 [[1.         0.70588235 0.84887469 0.70588235 0.84887469]
 [0.70588235 1.         0.36380344 0.88235294 0.36380344]
 [0.84887469 0.36380344 1.         0.60633906 1.        ]
 [0.70588235 0.88235294 0.60633906 1.         0.60633906]
 [0.84887469 0.36380344 1.         0.60633906 1.        ]]
영화별 유사도
 [[1.         0.70588235 0.84887469 0.70588235 0.84887469]
 [0.70588235 1.         0.36380344 0.88235294 0.36380344]
 [0.84887469 0.36380344 1.         0.60633906 1.        ]
 [0.70588235 0.88235294 0.60633906 1.         0.60633906]
 [0.84887469 0.36380344 1.         0.60633906 1.        ]]
내적
 [[11.63987219  6.09776035 12.39549875  8.28058098 12.39549875]
 [16.28693101 12.8036427  15.66972969 15.22175745 15.66972969]
 [ 8.64705882  9.76470588  6.18465844  9.52941176  6.18465844]]


>사용자 평점은 df_ratings_movies에 있다. 배열로 값을 추출하기 위해 values 값을 사용했다. 영화별 유사도는 movies_similarity이며 movies_similarity을 DataFrame로 변환시킨  item_based_collab.values를 이용할 수도 있다. 이 두 가지를 이용하여 간단하게 내적을 구할 수 있다.

In [ ]:
import numpy as np

print(np.abs(movies_similarity))
print(np.abs(movies_similarity).sum(axis=1))
print(np.array([np.abs(movies_similarity).sum(axis=1)]))


[[1.         0.70588235 0.84887469 0.70588235 0.84887469]
 [0.70588235 1.         0.36380344 0.88235294 0.36380344]
 [0.84887469 0.36380344 1.         0.60633906 1.        ]
 [0.70588235 0.88235294 0.60633906 1.         0.60633906]
 [0.84887469 0.36380344 1.         0.60633906 1.        ]]
[4.10951408 3.31584217 3.81901719 3.80091342 3.81901719]
[[4.10951408 3.31584217 3.81901719 3.80091342 3.81901719]]


>유사도의 절대값을 표현하기 위해 abs()함수를 이용했다. 절대값의 합을 구하기 위해 sum()함수를 이용했으며 열에 따른 합을 구하기 위해 axis옵션을 추가했다. 마지막으로 이전에 구한 내적이 2차원 배월로 되어 있어 형식을 맞추기 위해 2차원 배열로 값을 출력했다.

In [ ]:
def predict_rating(ratings_arr, item_sim_arr):
  return ratings_arr.dot(item_sim_arr)/np.array([np.abs(item_sim_arr).sum(axis=1)])

ratings_pred = predict_rating(df_ratings_movies.values, movies_similarity)  
ratings_pred

array([[2.83242056, 1.83897786, 3.24573002, 2.17857658, 3.24573002],
       [3.9632255 , 3.86135469, 4.10307912, 4.004763  , 4.10307912],
       [2.10415603, 2.9448645 , 1.61943718, 2.50713729, 1.61943718]])

>지금까지 내용을 간단하게 함수화 하여 결과를 출력해 보았다. 

In [ ]:
ratings_pred_matrix = pd.DataFrame(data=ratings_pred, index=df_ratings_movies.index, columns = df_ratings_movies.columns)
ratings_pred_matrix

movieName   7번방의 선물      국가대표      국제시장        명랑      연평대전
userID                                                     
user1      2.832421  1.838978  3.245730  2.178577  3.245730
user2      3.963226  3.861355  4.103079  4.004763  4.103079
user3      2.104156  2.944864  1.619437  2.507137  1.619437

> 좀 더 보기 편하게 하기 위해 dataframe으로 만들었다. 위의 내용이 예측 점수가 된다.