#1. 데이터 읽기

In [ ]:
import pandas as pd 
from sklearn.datasets import load_breast_cancer

cancer = load_breast_cancer()
df = pd.DataFrame(data=cancer.data, columns=cancer.feature_names) 
df["class"] = cancer.target 
df.head()

mean radius  mean texture  ...  worst fractal dimension  class
0        17.99         10.38  ...                  0.11890      0
1        20.57         17.77  ...                  0.08902      0
2        19.69         21.25  ...                  0.08758      0
3        11.42         20.38  ...                  0.17300      0
4        20.29         14.34  ...                  0.07678      0

[5 rows x 31 columns]

#2. 모델 만들기
> voting_classifier(분류기 리스트, voting="보팅기법")으로 선언해주어야 한다.

In [ ]:
from sklearn.linear_model import LogisticRegression 
from sklearn.neighbors import KNeighborsClassifier 
from sklearn.model_selection import train_test_split 
from sklearn.ensemble import VotingClassifier 
from sklearn.metrics import accuracy_score 

# 가장 마지막에 label이 저장되어 있어 -1로 표현함.
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,:-1], df.iloc[:,-1],test_size=0.2) 
# 로지스틱 회귀
lr = LogisticRegression(max_iter=4000) 
# KNN
knn = KNeighborsClassifier() 
vo = VotingClassifier([("lr", lr), ("knn", knn)], voting="soft") 
vo.fit(X_train, y_train) 
y_pred = vo.predict(X_test) 

print("정확도 : {}\n\n".format(accuracy_score(y_test, y_pred))) 

정확도 : 0.9649122807017544




In [ ]:
for clf in [lr, knn]: 
  print('클래스 정보 확인 ',clf.__class__)
  clf_name = clf.__class__.__name__
  clf.fit(X_train, y_train) 
  y_pred = clf.predict(X_test) 
  acc = accuracy_score(y_test, y_pred) 
  print("{}'s 정확도 : {}'".format(clf_name,acc))

클래스 정보 확인  <class 'sklearn.linear_model._logistic.LogisticRegression'>
LogisticRegression's 정확도 : 0.9824561403508771'
클래스 정보 확인  <class 'sklearn.neighbors._classification.KNeighborsClassifier'>
KNeighborsClassifier's 정확도 : 0.9385964912280702'


> 다음과 같은 경고가 나타날 경우 lr의 max_iter의 수치를 올린다.

>Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html

>Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)

#3. 스케일링을 통한 모델 성능 높이기
> 로지스틱 회귀의 경우 데이터를 스케일링하게 되면 성능이 향상됨으로 StandardScaler를 통해 스케일링을 진행해 보자

In [ ]:
from sklearn.preprocessing import StandardScaler 

X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,:-1], df.iloc[:,-1],test_size=0.2, random_state=62) 
lr = LogisticRegression(max_iter=4000) 
knn = KNeighborsClassifier() 
vo = VotingClassifier([("lr", lr), ("knn", knn)], voting="soft") 
vo.fit(X_train, y_train) 
y_pred = vo.predict(X_test) 

print("정확도 : {}\n\n".format(accuracy_score(y_test, y_pred))) 

for clf in [lr, knn]: 
  print('클래스 정보 확인 ',clf.__class__)
  clf_name = clf.__class__.__name__
  clf.fit(X_train, y_train) 
  y_pred = clf.predict(X_test) 
  acc = accuracy_score(y_test, y_pred) 
  print("{}'s 정확도 : {}'".format(clf_name,acc))
print('===============================================================')


scaler = StandardScaler() 
X_train = scaler.fit_transform(X_train) 

scaler = StandardScaler() 
X_test = scaler.fit_transform(X_test) 

vo = VotingClassifier([("lr", lr), ("knn", knn)], voting="soft") 

vo.fit(X_train, y_train) 
y_pred = vo.predict(X_test) 

print("정확도 : {}".format(accuracy_score(y_test, y_pred))) 

for clf in [lr, knn]: 
  clf_name = clf.__class__.__name__ 
  clf.fit(X_train, y_train) 
  y_pred = clf.predict(X_test) 
  acc = accuracy_score(y_test, y_pred) 
  print("{}'s acc : {}'".format(clf_name,acc))

정확도 : 0.9298245614035088


클래스 정보 확인  <class 'sklearn.linear_model._logistic.LogisticRegression'>
LogisticRegression's 정확도 : 0.9298245614035088'
클래스 정보 확인  <class 'sklearn.neighbors._classification.KNeighborsClassifier'>
KNeighborsClassifier's 정확도 : 0.9122807017543859'
정확도 : 0.9736842105263158
LogisticRegression's acc : 0.9824561403508771'
KNeighborsClassifier's acc : 0.956140350877193'


#4. 교차검증

In [ ]:
import numpy as np
from sklearn.model_selection import cross_val_score 

for clf in [vo, lr, knn]:
  # 위에서 표준화 작업을 진행하여 두 값을 합치기 위해 concatenate을 이용한다.
  scores = cross_val_score(clf, np.concatenate((X_train,X_test)), 
                           np.concatenate((y_train, y_test)), 
                           scoring="accuracy", cv=5) 
  print(clf.__class__.__name__) 
  print(scores) 
  print(np.mean(scores)) 
  print()

VotingClassifier
[0.96491228 0.99122807 0.99122807 0.98245614 0.97345133]
0.9806551777674274

LogisticRegression
[0.94736842 0.97368421 0.99122807 0.99122807 0.98230088]
0.9771619313771154

KNeighborsClassifier
[0.95614035 0.96491228 0.97368421 0.94736842 0.95575221]
0.9595714951094549



#5. 튜닝
> 하이퍼 파라미터 설정 시 이전 VotingClassifier에서 설정한 쌍따옴표 안의 문자와 언더바(_) 두 개를 이어서 파라미터를 설정할 수 있다.

In [ ]:
from sklearn.model_selection import GridSearchCV

def get_best_hyper_paramerter(logreg_list, n_neighbors_list):
  params =  {
    'lr__C' : logreg_list,
    'knn__n_neighbors' : n_neighbors_list,
    'knn__weights' : ["uniform", "distance"],
    'knn__metric' : ['euclidean', 'manhattan', 'minkowski']
  }

  grid_cv = GridSearchCV(vo, param_grid=params, scoring='accuracy', cv=5)
  grid_cv.fit(X_train, y_train)
  print('Best Score: ', grid_cv.best_score_)
  print('Best Hyper Parameter: ', grid_cv.best_params_)

> 파라미터는 알고리즘마다 다르게 나타나며 각 알고리즘에 맞는 파라미터를 지정하기 위해 3번에서 VotingClassifier에 적용된 값을 사용하여 lr__C 형식으로 만들게 된다.

In [ ]:
cost_list =  [0.001, 0.01, 0.1, 1, 10]
n_neighbors_list =  range(1, 90, 10)

get_best_hyper_paramerter(cost_list, n_neighbors_list)

Best Score:  0.9758241758241759
Best Hyper Parameter:  {'knn__metric': 'euclidean', 'knn__n_neighbors': 61, 'knn__weights': 'distance', 'lr__C': 10}


In [ ]:
cost_list =  range(2, 22, 4)
n_neighbors_list =  range(52, 70, 3)

get_best_hyper_paramerter(cost_list, n_neighbors_list)

Best Score:  0.9758241758241759
Best Hyper Parameter:  {'knn__metric': 'euclidean', 'knn__n_neighbors': 58, 'knn__weights': 'uniform', 'lr__C': 10}


In [ ]:
cost_list =  range(7, 13, 1)
n_neighbors_list =  range(56, 60, 1)

get_best_hyper_paramerter(cost_list, n_neighbors_list)

Best Score:  0.9758241758241759
Best Hyper Parameter:  {'knn__metric': 'euclidean', 'knn__n_neighbors': 56, 'knn__weights': 'distance', 'lr__C': 10}
