In [ ]:
docs = [
        '여름엔 과일이 맛있다', 
        '여름엔 수박이 맛있다',
        '여름엔 바다지',
        '여름엔 과일이 맛없다']

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
vect = CountVectorizer()

In [ ]:
countvect = vect.fit_transform(docs)

In [ ]:
countvect_array = countvect.toarray()
countvect_array

array([[1, 0, 1, 0, 0, 1],
       [0, 0, 1, 0, 1, 1],
       [0, 0, 0, 1, 0, 1],
       [1, 1, 0, 0, 0, 1]])

In [ ]:
for idx in countvect_array:
  print(idx)

[1 0 1 0 0 1]
[0 0 1 0 1 1]
[0 0 0 1 0 1]
[1 1 0 0 0 1]


In [ ]:
import numpy as np

v1 = countvect_array[0]
val_square = np.square(v1)
val_square_sum = sum(val_square)
n1 = np.sqrt(val_square_sum)

for val in countvect_array:
  val_square = np.square(val)
  val_square_sum = sum(val_square)
  n2 = np.sqrt(val_square_sum)
  denominator = n1*n2
  numerator = np.dot(v1, val)
  cos_similarity = numerator / denominator
  print(cos_similarity)

1.0000000000000002
0.6666666666666667
0.40824829046386296
0.6666666666666667


> 중복 유무에 따른 결과를 비교하려 두 값을 확인했지만 결국은 같은 결과가 나타났다. 이로 인해 중복된 값이 결과에 영향을 미치지는 않는다는 것이다.

In [ ]:
docs2 = [
        '여름엔 과일이 맛있다 여름엔 과일이 맛있다', 
        '여름엔 수박이 맛있다',
        '여름엔 바다지',
        '여름엔 과일이 맛없다'
        ]

In [ ]:
import numpy as np

def norm(v):
  return np.sqrt(sum(np.square(v)))

def cos_similarity(v1, v2):
  return np.dot(v1, v2) / norm(v1)*norm(v2)

>위의 식을 이용하여 간단하게 함수를 만들었다. 
* dot(a, b) : a와 b의 곱의 합
* square() : 제곱
* sum() : 합
* sqrt : 루트