# Quiz
> tmdb_5000_movies 에서 overview 를 이용한 추천 시스템을 구축하시오.
* 코드 완성 후 [Quiz_이름.ipynb]로 제출

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [2]:
import pandas as pd

filepath = '/content/drive/MyDrive/Colab Notebooks/5. 컨텐츠 기반/data/tmdb_5000_movies.csv'
df = pd.read_csv(filepath)
df.head()

budget  ... vote_count
0  237000000  ...      11800
1  300000000  ...       4500
2  245000000  ...       4466
3  250000000  ...       9106
4  260000000  ...       2124

[5 rows x 20 columns]

In [3]:
columns = ['id', 'title', 'genres', 'vote_average', 'vote_count', 'popularity', 'keywords', 'overview']
df_movies = df[columns]
df_movies

id  ...                                           overview
0      19995  ...  In the 22nd century, a paraplegic Marine is di...
1        285  ...  Captain Barbossa, long believed to be dead, ha...
2     206647  ...  A cryptic message from Bond’s past sends him o...
3      49026  ...  Following the death of District Attorney Harve...
4      49529  ...  John Carter is a war-weary, former military ca...
...      ...  ...                                                ...
4798    9367  ...  El Mariachi just wants to play his guitar and ...
4799   72766  ...  A newlywed couple's honeymoon is upended by th...
4800  231617  ...  "Signed, Sealed, Delivered" introduces a dedic...
4801  126186  ...  When ambitious New York attorney Sam is sent t...
4802   25975  ...  Ever since the second grade when he first saw ...

[4803 rows x 8 columns]

> 결측치 확인

In [4]:
df_movies.isnull().sum()

id              0
title           0
genres          0
vote_average    0
vote_count      0
popularity      0
keywords        0
overview        3
dtype: int64

In [5]:
df_movies[df_movies['overview'].notnull()].reset_index()

index  ...                                           overview
0         0  ...  In the 22nd century, a paraplegic Marine is di...
1         1  ...  Captain Barbossa, long believed to be dead, ha...
2         2  ...  A cryptic message from Bond’s past sends him o...
3         3  ...  Following the death of District Attorney Harve...
4         4  ...  John Carter is a war-weary, former military ca...
...     ...  ...                                                ...
4795   4798  ...  El Mariachi just wants to play his guitar and ...
4796   4799  ...  A newlywed couple's honeymoon is upended by th...
4797   4800  ...  "Signed, Sealed, Delivered" introduces a dedic...
4798   4801  ...  When ambitious New York attorney Sam is sent t...
4799   4802  ...  Ever since the second grade when he first saw ...

[4800 rows x 9 columns]

In [6]:
df_movies_notnull = df_movies[df_movies['overview'].notnull()]
df_movies_notnull

id  ...                                           overview
0      19995  ...  In the 22nd century, a paraplegic Marine is di...
1        285  ...  Captain Barbossa, long believed to be dead, ha...
2     206647  ...  A cryptic message from Bond’s past sends him o...
3      49026  ...  Following the death of District Attorney Harve...
4      49529  ...  John Carter is a war-weary, former military ca...
...      ...  ...                                                ...
4798    9367  ...  El Mariachi just wants to play his guitar and ...
4799   72766  ...  A newlywed couple's honeymoon is upended by th...
4800  231617  ...  "Signed, Sealed, Delivered" introduces a dedic...
4801  126186  ...  When ambitious New York attorney Sam is sent t...
4802   25975  ...  Ever since the second grade when he first saw ...

[4800 rows x 8 columns]

> 이상치 확인

In [7]:
df_movies_notnull.describe()

id  vote_average    vote_count   popularity
count    4800.000000   4800.000000   4800.000000  4800.000000
mean    56967.252917      6.092917    690.645208    21.505403
std     88350.548128      1.191468   1234.853376    31.822273
min         5.000000      0.000000      0.000000     0.000000
25%      9012.750000      5.600000     54.000000     4.682212
50%     14623.500000      6.200000    236.000000    12.928897
75%     58512.500000      6.800000    737.250000    28.350628
max    447027.000000     10.000000  13752.000000   875.581305

> 단어 메트릭스 생성

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer

vect = TfidfVectorizer(max_df=500)
count_vect = vect.fit_transform(df_movies_notnull['overview']).toarray()
count_vect

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [9]:
df_vect = pd.DataFrame(count_vect, columns=sorted(vect.vocabulary_))
df_vect

00  000  007  07am   10  100  ...  æon  éloigne  émigré  été  única  über
0     0.0  0.0  0.0   0.0  0.0  0.0  ...  0.0      0.0     0.0  0.0    0.0   0.0
1     0.0  0.0  0.0   0.0  0.0  0.0  ...  0.0      0.0     0.0  0.0    0.0   0.0
2     0.0  0.0  0.0   0.0  0.0  0.0  ...  0.0      0.0     0.0  0.0    0.0   0.0
3     0.0  0.0  0.0   0.0  0.0  0.0  ...  0.0      0.0     0.0  0.0    0.0   0.0
4     0.0  0.0  0.0   0.0  0.0  0.0  ...  0.0      0.0     0.0  0.0    0.0   0.0
...   ...  ...  ...   ...  ...  ...  ...  ...      ...     ...  ...    ...   ...
4795  0.0  0.0  0.0   0.0  0.0  0.0  ...  0.0      0.0     0.0  0.0    0.0   0.0
4796  0.0  0.0  0.0   0.0  0.0  0.0  ...  0.0      0.0     0.0  0.0    0.0   0.0
4797  0.0  0.0  0.0   0.0  0.0  0.0  ...  0.0      0.0     0.0  0.0    0.0   0.0
4798  0.0  0.0  0.0   0.0  0.0  0.0  ...  0.0      0.0     0.0  0.0    0.0   0.0
4799  0.0  0.0  0.0   0.0  0.0  0.0  ...  0.0      0.0     0.0  0.0    0.0   0.0

[4800 rows x 21222 columns]

> 코사인 거리 계산

In [10]:
from sklearn.metrics.pairwise import cosine_similarity, euclidean_distances

cosine_similarity = cosine_similarity(df_vect, df_vect)
cosine_similarity

array([[1.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 1.        , 0.01757941, ..., 0.01979731, 0.        ,
        0.        ],
       [0.        , 0.01757941, 1.        , ..., 0.01396903, 0.        ,
        0.        ],
       ...,
       [0.        , 0.01979731, 0.01396903, ..., 1.        , 0.0153634 ,
        0.00658588],
       [0.        , 0.        , 0.        , ..., 0.0153634 , 1.        ,
        0.01834285],
       [0.        , 0.        , 0.        , ..., 0.00658588, 0.01834285,
        1.        ]])

In [11]:
overview_sim_sorted = cosine_similarity.argsort()[:,::-1]
overview_sim_sorted

array([[   0, 3603, 2130, ..., 3082, 3081, 2399],
       [   1, 2542, 3094, ..., 2952, 2951,    0],
       [   2, 1343, 4070, ..., 2925, 2923,    0],
       ...,
       [4797, 4033, 1043, ..., 3368, 3369,    0],
       [4798, 2027, 1796, ..., 2430, 2429,    0],
       [4799, 4099, 2586, ..., 2826, 2825,    0]])

> 데이터 입력

In [12]:
# 영화 이름을 입력 받으면 index 정보 찾기
movie_name = input('영화 제목 : ')
recommand_movies = df_movies_notnull[df_movies_notnull['title'].str.lower().str.contains(movie_name.lower())]
recommand_movies

영화 제목 : piRatE


id  ...                                           overview
1        285  ...  Captain Barbossa, long believed to be dead, ha...
12        58  ...  Captain Jack Sparrow works his way out of a bl...
17      1865  ...  Captain Jack Sparrow crosses paths with a woma...
199       22  ...  Jack Sparrow, a freewheeling 17th-century pira...
848    72197  ...  The luxuriantly bearded Pirate Captain is a bo...
1709  192577  ...  Space Pirate Captain Harlock and his fearless ...
2590   15511  ...  Set Sail For Adventure! A boatload of beloved ...
3184   10179  ...  The time is the distant future, where by far t...
3820   35032  ...  A girl is engaged to the local richman, but me...

[9 rows x 8 columns]

> 입력 받은 데이터를 기준으로 상위 10개 데이터 추출

In [21]:
for movie_name in recommand_movies['title'] :
  title_movie = df_movies[df_movies['title'] == movie_name]
  recommand = overview_sim_sorted[title_movie.index.values, 1:11]
  recommand_movie = df_movies.iloc[recommand.reshape(-1)]
  print('movie : ', title_movie['title'].values[0])
  print(recommand_movie[['title', 'overview']])
  print('===================================================================================')
  print('')

movie :  Pirates of the Caribbean: At World's End
                              title                                           overview
2542  What's Love Got to Do with It  A film about the singer Tina Turner and how sh...
3094           The Brothers Solomon  A pair of well-meaning, but socially inept bro...
1280                      Disturbia  Kale is a 17-year-old placed under house arres...
2102                The Descendants  With his wife Elizabeth on life support after ...
3631             Heavenly Creatures  Based on the true story of Juliet Hulme and Pa...
792                Just Like Heaven  Shortly after David Abbott moves into his new ...
4421                  Truth or Dare  A group of college friends celebrate the end o...
4758                     The Signal  Three college students on a road trip across t...
2120                         Orphan  A married couple with a rocky past adopt 9-yea...
1709   Space Pirate Captain Harlock  Space Pirate Captain Harlock and his fearle

> 상위 단어 50개

In [22]:
df_vect.sum().sort_values(ascending=False).head(50)

family     49.433762
story      45.010917
find       43.284349
all        42.893851
love       41.160960
about      40.770970
must       40.406591
this       40.389913
have       38.490468
them       38.299332
will       36.386894
old        36.220182
father     35.629780
woman      35.472224
only       35.363197
where      34.873517
friends    33.499275
time       33.211048
school     32.867493
finds      32.824875
years      32.755055
town       32.464961
can        32.330175
get        32.319379
while      31.932996
war        31.220434
back       31.127258
film       31.074528
year       31.035147
lives      30.578683
home       30.069088
help       29.737413
city       29.593401
three      28.847953
group      28.448180
becomes    28.334235
was        28.298266
not        28.291673
what       28.271151
son        28.266157
own        27.735386
way        27.661143
girl       27.603449
wife       27.502963
high       27.323290
which      27.321058
against    27.190249
during     26